### ISSUE TITLE
automatic disk selection selects installation medium with persistence partition

### ISSUE THREAD

**Issue by pdxkay** [brennanfee/linux-bootstraps#64]
Situation: Booted usb debian live image with persistence.
usb disk: /dev/sda 8gib
wanted root disk: /dev/nvme0n1 512gib

Thoughts on this issue:
* Automatic disk selection shouldn't consider mounted disk with mounted partitions (in my opinion--but if you're doing this for a reason, then ok.)
* Automatic disk selection shouldn't consider disks below a size threshold (10gib?)

Here's the output where I watched the install script destroy it's own installation medium (lol)

```
Unmounting partitions
umount: /mnt: not mounted
Wiping disks
    Wiping main disk partitions
/dev/sda: 2 bytes were erased at offset 0x000001fe (dos): 55 aa
100+0 records in
100+0 records out
51200 bytes (51 kB, 50 KiB) copied, 0.00019276 s, 266 MB/s
100+0 records in
100+0 records out
51200 bytes (51 kB, 50 KiB) copied, 16.3215 s, 3.1 kB/s
Creating main partitions
    Creating partition table
Wiping disks
    Wiping main disk partitions
/dev/sda: 2 bytes were erased at offset 0x000001fe (dos): 55 aa
100+0 records in
100+0 records out
51200 bytes (51 kB, 50 KiB) copied, 0.00019276 s, 266 MB/s
100+0 records in
100+0 records out
```

**Comment by pdxkay** [comment]
Also, other selection criteria should also be considered. I will likely stop using <10gib flash drives soon anyways. I am leaning toward my first thought.

**Comment by brennanfee** [comment]
Yeah, I think excluding already mounted partitions is the right course of action initially.  No matter what, we shouldn't be installing to those.  As for smaller partitions, if it continues to come up in various scenarios we could add another change, but we both know that mounted partitions should be off limits.

Working on a fix now.
